# To activate, change the Appveyor settings to use `.appveyor.yml`.
environment:
  PYPY_PY2_VERSION: 2.7
  PYPY_PY3_VERSION: 3.6
  PYPY_VERSION: 7.3.2
install:
  - python -m pip install --upgrade tox virtualenv

  - ps: (New-Object Net.WebClient).DownloadFile("https://downloads.python.org/pypy/pypy${env:PYPY_PY2_VERSION}-v${env:PYPY_VERSION}-win32.zip", "$env:appveyor_build_folder\pypy${env:PYPY_PY2_VERSION}-v${env:PYPY_VERSION}-win32.zip")
  - ps: 7z x pypy${env:PYPY_PY2_VERSION}-v${env:PYPY_VERSION}-win32.zip | Out-Null
  - move pypy%PYPY_PY2_VERSION%-v%PYPY_VERSION%-win32 C:\
  - 'SET PATH=C:\pypy%PYPY_PY2_VERSION%-v%PYPY_VERSION%-win32\;%PATH%'

  - ps: (New-Object Net.WebClient).DownloadFile("https://downloads.python.org/pypy/pypy${env:PYPY_PY3_VERSION}-v${env:PYPY_VERSION}-win32.zip", "$env:appveyor_build_folder\pypy${env:PYPY_PY3_VERSION}-v${env:PYPY_VERSION}-win32.zip")
  - ps: 7z x pypy${env:PYPY_PY3_VERSION}-v${env:PYPY_VERSION}-win32.zip | Out-Null
  - move pypy%PYPY_PY3_VERSION%-v%PYPY_VERSION%-win32 C:\
  - 'SET PATH=C:\pypy%PYPY_PY3_VERSION%-v%PYPY_VERSION%-win32\;%PATH%'

build: off

test_script:
  - python -m tox --skip-missing-interpreters=false
