[tox]
skip_missing_interpreters = True
envlist = py,pypy3

[testenv]
deps = -rrequirements-dev.txt
setenv = PYFLAKES_ERROR_UNKNOWN=1
commands =
    python --version --version
    coverage erase
    coverage run -m unittest discover pyflakes {posargs}
    coverage report
    flake8 pyflakes setup.py

[flake8]
max_line_length = 89
