name: Test

on:
  pull_request:
  push:
    branches: [main, 'test-me-*']
    tags: ['*']

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11.0-beta - 3.11.999", "pypy-3.9"]
        os: [ubuntu-latest]
        # Include minimum py3 + maximum py3 + pypy3 on Windows
        include:
          - { os: "windows-latest" , python-version: "3.6" }
          - { os: "windows-latest" , python-version: "3.10" }
          - { os: "windows-latest" , python-version: "pypy-3.9" }

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: python -m pip install -U tox

      - name: Tox tests
        run: tox -e py
